name: flutter_auth
description: "Flutter project to demo multiple authentication strategies."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.8.0
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter

  # caching
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # DI
  get_it: ^8.2.0
  injectable: ^2.5.1

  # firebase
  firebase_core: ^4.0.0

  # functional
  fpdart: ^1.1.1

  # i18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  slang: ^4.8.1
  slang_flutter: ^4.8.0

  # network
  dio: ^5.8.0+1
  internet_connection_checker_plus: ^2.7.2

  # routing
  go_router: ^16.0.0

  # state management
  flutter_bloc: ^9.1.1

  # UI helpers
  flutter_screenutil: ^5.9.3

  # UI components
  bot_toast: ^4.1.3

  # utils
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  logger: ^2.6.1
  package_info_plus: ^8.3.0

dev_dependencies:
  # code analyzers
  very_good_analysis: ^9.0.0

  # generators
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^3.2.0
  injectable_generator: ^2.8.1
  json_serializable: ^6.10.0

  # testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.5.0

flutter:
  uses-material-design: true
