// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDltKYSd3cY1A8Y_pKyVMcqC-FNC2_7BSU',
    appId: '1:798992916814:android:91841b343a03dba83f7e1f',
    messagingSenderId: '798992916814',
    projectId: 'nashcrate-flutter-showcase',
    storageBucket: 'nashcrate-flutter-showcase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyhRVS8s5P5dXAq0iAYdW13-RGpSv2hNs',
    appId: '1:798992916814:ios:3e746fcc6b2589783f7e1f',
    messagingSenderId: '798992916814',
    projectId: 'nashcrate-flutter-showcase',
    storageBucket: 'nashcrate-flutter-showcase.firebasestorage.app',
    iosClientId: '798992916814-qgrh9272ob7sag6gj7m8od0gm1vo0me6.apps.googleusercontent.com',
    iosBundleId: 'com.nashcrate.flutterShowcase',
  );

}